# Site settings
title: uDev.be
description: >
  You develop
baseurl: ""
url: "https://udev.be"
avatar: "images/udev_logo.png"
github_username:  udevbe
repository: udevbe/udevbe.github.io
gems: ['jekyll-github-metadata']

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
